### ISSUE TITLE
Ambiguous use of 'init()'

### ISSUE THREAD

**Issue by davidhenze** [bradhowes/swift-math-parser#1]
Updated Xcode from 14.2 to 14.3 and now it is giving a warning "Ambiguous use of 'init()'" for line 316 of MathParser.swift ("End()" is highlighted):

```swift
/// Parser for a math expression. Checks that there is nothing remaining to be parsed.
  private lazy var expression = Parse {
    additionAndSubtraction
    ignoreSpaces
    End()
  }
```

**Comment by bradhowes** [comment]
Thanks for the heads-up. I've pushed a fix.
